import type { QuoteListResponse } from "@/shared/api/generated/schemas";

const MOCK_SHIPPER_QUOTES: QuoteListResponse[] = [
  {
    quoteId: 5101,
    quotePublicId: "mock-quote-5101",
    truckId: 1,
    originAddress: "서울특별시 금천구 가산동",
    destinationAddress: "경기도 성남시 분당구 정자동",
    distanceKm: 29.4,
    vehicleType: "TON_1",
    vehicleBodyType: "CARGO",
    cargoName: "전자부품",
    desiredPrice: 148000,
    finalPrice: 0,
    status: "OPEN",
    createdAt: "2026-02-22T10:20:00.000Z",
  },
  {
    quoteId: 5102,
    quotePublicId: "mock-quote-5102",
    truckId: 2,
    originAddress: "인천광역시 연수구 송도동",
    destinationAddress: "경기도 화성시 동탄면",
    distanceKm: 54.1,
    vehicleType: "TON_2_5",
    vehicleBodyType: "WING_BODY",
    cargoName: "패키지 박스",
    desiredPrice: 0,
    finalPrice: 0,
    status: "OPEN",
    createdAt: "2026-02-21T06:35:00.000Z",
  },
  {
    quoteId: 5103,
    quotePublicId: "mock-quote-5103",
    truckId: 3,
    originAddress: "부산광역시 강서구 명지동",
    destinationAddress: "울산광역시 남구 삼산동",
    distanceKm: 41.3,
    vehicleType: "TON_3_5",
    vehicleBodyType: "WING_BODY",
    cargoName: "의류 박스",
    desiredPrice: 265000,
    finalPrice: 265000,
    status: "ASSIGNED",
    createdAt: "2026-02-20T03:45:00.000Z",
  },
  {
    quoteId: 5104,
    quotePublicId: "mock-quote-5104",
    truckId: 4,
    originAddress: "대구광역시 북구 검단동",
    destinationAddress: "경상북도 구미시 공단동",
    distanceKm: 33.2,
    vehicleType: "TON_5",
    vehicleBodyType: "CARGO",
    cargoName: "산업 자재",
    desiredPrice: 179000,
    finalPrice: 179000,
    status: "PICKUP",
    createdAt: "2026-02-19T07:15:00.000Z",
  },
  {
    quoteId: 5105,
    quotePublicId: "mock-quote-5105",
    truckId: 5,
    originAddress: "광주광역시 광산구 하남동",
    destinationAddress: "전라북도 전주시 덕진구",
    distanceKm: 88.6,
    vehicleType: "TON_5",
    vehicleBodyType: "WING_BODY",
    cargoName: "가공 식품",
    desiredPrice: 312000,
    finalPrice: 312000,
    status: "TRANSIT",
    createdAt: "2026-02-18T09:30:00.000Z",
  },
  {
    quoteId: 5201,
    quotePublicId: "mock-quote-5201",
    truckId: 6,
    originAddress: "대전광역시 유성구 관평동",
    destinationAddress: "충청북도 청주시 흥덕구",
    distanceKm: 42.8,
    vehicleType: "TON_2_5",
    vehicleBodyType: "CARGO",
    cargoName: "반도체 장비 부품",
    desiredPrice: 221000,
    finalPrice: 229000,
    status: "DROPOFF",
    createdAt: "2026-02-17T11:00:00.000Z",
  },
  {
    quoteId: 5202,
    quotePublicId: "mock-quote-5202",
    truckId: 7,
    originAddress: "경기도 김포시 양촌읍",
    destinationAddress: "서울특별시 송파구 문정동",
    distanceKm: 38.9,
    vehicleType: "TON_1",
    vehicleBodyType: "CARGO",
    cargoName: "생활용품",
    desiredPrice: 136000,
    finalPrice: 141000,
    status: "DROPOFF",
    createdAt: "2026-02-16T04:55:00.000Z",
  },
  {
    quoteId: 5203,
    quotePublicId: "mock-quote-5203",
    truckId: 8,
    originAddress: "경상남도 창원시 성산구",
    destinationAddress: "부산광역시 사상구 감전동",
    distanceKm: 47.6,
    vehicleType: "TON_3_5",
    vehicleBodyType: "WING_BODY",
    cargoName: "기계 부속",
    desiredPrice: 258000,
    finalPrice: 271000,
    status: "DROPOFF",
    createdAt: "2026-02-15T01:40:00.000Z",
  },
  {
    quoteId: 5301,
    quotePublicId: "mock-quote-5301",
    truckId: 9,
    originAddress: "강원특별자치도 원주시 문막읍",
    destinationAddress: "경기도 이천시 부발읍",
    distanceKm: 73.5,
    vehicleType: "TON_5",
    vehicleBodyType: "CARGO",
    cargoName: "건축 자재",
    desiredPrice: 298000,
    finalPrice: 0,
    status: "CANCELED",
    createdAt: "2026-02-14T08:10:00.000Z",
  },
  {
    quoteId: 5302,
    quotePublicId: "mock-quote-5302",
    truckId: 10,
    originAddress: "충청남도 아산시 탕정면",
    destinationAddress: "세종특별자치시 반곡동",
    distanceKm: 31.7,
    vehicleType: "TON_1",
    vehicleBodyType: "CARGO",
    cargoName: "문서/소형박스",
    desiredPrice: 118000,
    finalPrice: 0,
    status: "CANCELLED",
    createdAt: "2026-02-13T05:25:00.000Z",
  },
  {
    quoteId: 5303,
    quotePublicId: "mock-quote-5303",
    truckId: 11,
    originAddress: "제주특별자치도 제주시 애월읍",
    destinationAddress: "제주특별자치도 서귀포시 대정읍",
    distanceKm: 56.2,
    vehicleType: "TON_2_5",
    vehicleBodyType: "WING_BODY",
    cargoName: "신선식품",
    desiredPrice: 207000,
    finalPrice: 0,
    status: "CANCELED",
    createdAt: "2026-02-12T02:05:00.000Z",
  },
];

export function listMockShipperQuotesByCase(): QuoteListResponse[] {
  return MOCK_SHIPPER_QUOTES.map((quote) => ({ ...quote }));
}
