import type { SettlementApprovalRow } from "@/features/settlements/model/types";

export const SETTLEMENT_APPROVAL_MOCK_ROWS: SettlementApprovalRow[] = [
  {
    settlementId: "S-5001",
    matchId: "M-3301",
    driverId: "D-1201",
    driverName: "김민수",
    shipperName: "한빛물류",
    dueDate: "2026-02-14",
    totalFare: 620000,
    driverPayout: 521000,
    settlementStatus: "PENDING",
    approvalStatus: "PENDING",
  },
  {
    settlementId: "S-5002",
    matchId: "M-3302",
    driverId: "D-1202",
    driverName: "박지훈",
    shipperName: "더원화학",
    dueDate: "2026-02-14",
    totalFare: 780000,
    driverPayout: 640000,
    settlementStatus: "PROCESSING",
    approvalStatus: "PENDING",
  },
  {
    settlementId: "S-4990",
    matchId: "M-3295",
    driverId: "D-1182",
    driverName: "최유진",
    shipperName: "선도로지스",
    dueDate: "2026-02-11",
    totalFare: 410000,
    driverPayout: 344000,
    settlementStatus: "COMPLETED",
    approvalStatus: "APPROVED",
    reviewMemo: "정산 증빙 확인 완료",
  },
  {
    settlementId: "S-4989",
    matchId: "M-3294",
    driverId: "D-1174",
    driverName: "정하늘",
    shipperName: "제이파츠",
    dueDate: "2026-02-11",
    totalFare: 390000,
    driverPayout: 315000,
    settlementStatus: "FAILED",
    approvalStatus: "REJECTED",
    reviewMemo: "운행 증빙 누락",
  },
];
